---
- hosts: 192.168.56.5
  sudo_user: base
  sudo: yes
  tasks:

  - name: Configurando NFDUMP
    copy: src=../../../vms/{{hostname}}/etc/nfdump dest=/etc/default/nfdump owner=root group=root mode=644
